name: Test generate-metadata-action

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - 'README.md'

jobs:
  action-run:
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.action-run.outputs.filepath }}
    steps:
      - name: 'Checkout directory'
        uses: actions/checkout@v2
      - uses: ./
      - name: Generate metadata file
        id: generate_metadata
        uses: hashicorp/actions-generate-metadata@main
        with:
          repository: ${{ github.event.repository.name }}
          version: make version

      - uses: actions/upload-artifact@v2
        with:
          name: metadata.json
          path: ${{ steps.generate_metadata.outputs.filepath }}
